#!/usr/bin/env perl
use FindBin qw($RealBin);
use lib $RealBin;
use lib '/home/bugzilla/devel/repos/github/dklawren/bugzilla-dev-manager';

use 5.10.0;
use Bz;
use Bz::App;

$| = 1;
Bz->config;
Bz::App->run;
