requires 'Class::Load', '0.22';
requires 'autodie';
requires 'File::Slurp';
requires 'App::Cmd';
requires 'Moo';
requires 'CGI';
requires 'File::Copy::Recursive';
requires 'JSON::XS';
requires 'Config::General';
requires 'DateTime';
requires 'REST::Client';
